#!/bin/sh
case $1 in
    fr)
        echo "French"
        ;;
    cs)
        echo "Czech"
        ;;
    pt_BR)
        echo "Brazilian Portuguese"
        ;;
    jp)
        echo "Japanese"
        ;;
    pl)
        echo "Polish"
        ;;
    it)
        echo "Italian"
        ;;
    zh_TW)
        echo "Traditional Chinese"
        ;;
    zh_CN)
        echo "Simplified Chinese"
        ;;
    hy)
        echo "Armenian"
        ;;
    en_GB)
        echo "English (United Kingdom)"
        ;;
    en_GB)
        echo "English (United Kingdom)"
        ;;
### MARKER TO ADD NEW LANGUAGE NAMES ###
    *)
        echo $1
        ;;
esac
