#!/bin/sh
case $1 in
    fr)
        echo "French"
        ;;
    cs)
        echo "Czech"
        ;;
    gl)
        echo "Galician"
        ;;
    sv)
        echo "Swedish"
        ;;
    nl)
        echo "Dutch"
        ;;
    ka)
        echo "Georgian"
        ;;
    tr)
        echo "Turkish"
        ;;
    fi)
        echo "Finnish"
        ;;
    ca)
        echo "Catalan"
        ;;
    hu)
        echo "Hungarian"
        ;;
    no)
        echo "Norwegian"
        ;;
    es)
        echo "Spanish"
        ;;
    de)
        echo "German"
        ;;
    lt)
        echo "Lithuanian"
        ;;
    ro)
        echo "Romanian"
        ;;
    mn)
        echo "Mongolian"
        ;;
    pt_BR)
        echo "Brazilian Portuguese"
        ;;
    jp)
        echo "Japanese"
        ;;
    pl)
        echo "Polish"
        ;;
    it)
        echo "Italian"
        ;;
    zh_TW)
        echo "Traditional Chinese"
        ;;
    zh_CN)
        echo "Simplified Chinese"
        ;;
    hy)
        echo "Armenian"
        ;;
    en_GB)
        echo "English (United Kingdom)"
        ;;
    en_GB)
        echo "English (United Kingdom)"
        ;;
### MARKER TO ADD NEW LANGUAGE NAMES ###
    *)
        echo $1
        ;;
esac
