#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

set -e

if [ -z "$1" -o -z "$2" ] ; then
    echo "Usage: ./admin/new-lang ll verbose_name"
    exit 1
fi

mkdir output/$1

sed -i "s/^\(LANGUAGES.*\)/\1 $1/" Makefile

sed -i "/### MARKER TO ADD NEW LANGUAGE NAMES ###/ i \\
    $1)
        /### MARKER TO ADD NEW LANGUAGE NAMES ###/ i \\
        echo \"$2\"
        /### MARKER TO ADD NEW LANGUAGE NAMES ###/ i \\
        ;;" get-lang-name

make

git add po/$1.po output/$1 pot/$1*.pot addendum/$1.sk
