#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

getname() {
    case $1 in
        Documentation.html)
            echo Main documentation
            ;;
        translators.html)
            echo List of translators
            ;;
        *)
            echo $1
            ;;
    esac
}

langname() {
    case $1 in
        fr)
            echo French
            ;;
        cs)
            echo Czech
            ;;
        pt_BR)
            echo Brazilian Portuguese
            ;;
        jp)
            echo Japanese
            ;;
        pl)
            echo Polish
            ;;
        zh_TW)
            echo Traditional Chinese
            ;;
        zh_CN)
            echo Simplified Chinese
            ;;
        hy)
            echo Armenian
            ;;
### MARKER TO ADD NEW LANGUAGE NAMES ###
        *)
            echo $1
            ;;
    esac
}

po4a \
    --msgid-bugs-address phpmyadmin-devel@lists.sourceforge.net \
    --copyright-holder "phpMyAdmin devel team" \
    --package-name phpMyAdmin-docs \
    -L utf-8 \
    -M utf-8 \
    -k 70 \
    po4a.conf
cat > output/index.html <<EOT
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US"
    version="-//W3C//DTD XHTML 1.1//EN" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>phpMyAdmin Localized Documentation</title>
</head>
<body>
<h1>phpMyAdmin Localized Documentation</h1>
<ul>
EOT

for loc in po/*.po ; do
    sed -i '
        s/SOME DESCRIPTIVE TITLE/phpMyAdmin documentation translation/;
        s/PACKAGE/phpMyAdmin-docs/;
        s/Report-Msgid-Bugs-To: .*\\n/Report-Msgid-Bugs-To: phpmyadmin-devel@lists.sf.net\\n/;
        s/(C) YEAR/(C) 2001 - '`date +%Y`'/;
        ' $loc
    lang=${loc%.po}
    lang=${lang#po/}
    (
        cd output/$lang
        rm -f index.html
        num=`ls | grep -v docs.css | grep -v favicon.ico | wc -l`
        files=`ls | grep -v docs.css | grep -v favicon.ico `
        cp ../../../phpmyadmin/docs.css .
        cp ../../../phpmyadmin/favicon.ico .
        cat > index.html <<EOT
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
    "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US"
    version="-//W3C//DTD XHTML 1.1//EN" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>phpMyAdmin `langname $lang` Documentation</title>
</head>
<body>
<h1>phpMyAdmin `langname $lang` Documentation</h1>
EOT
    if [ $num -eq 0 ] ; then
        cat >> index.html <<EOT
<p>Unfortunately no document is enough translated to `langname $lang`.</p>
EOT
        else
            echo "<li><a href="$lang">`langname $lang`</a><ul>" >> ../index.html
            cat >> index.html <<EOT
<p>Documents translated to `langname $lang`:</p>
<ul>
EOT
            for file in $files ; do
                echo "<li><a href=\"$file\">`getname $file`</a></li>" >> index.html
                echo "<li><a href=\"$lang/$file\">`getname $file`</a></li>" >> ../index.html
            done
            echo "</ul>" >> index.html
            echo "</ul></li>" >> ../index.html
        fi
        cat >> index.html <<EOT
</body>
</html>
EOT
    )
done
cat >> output/index.html <<EOT
</ul>
</body>
</html>
EOT
